<a href="https://colab.research.google.com/github/nabilaaaa24/data_mining/blob/main/Latihan_Modul_2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Analisis dataset penjualan untuk menemukan insight dasar tentang performa penjualan.
1. Memuat Data:


*   Import Library Pandas
*   Memuat dataset 'sales_data.csv' ke dalam DataFrame

In [ ]:
from google.colab import drive
drive.mount('/content/drive')

import pandas as pd

df = pd.read_csv('/content/drive/MyDrive/sales_data.csv')
df

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

,ORDERNUMBER,QUANTITYORDERED,PRICEEACH,ORDERLINENUMBER,SALES,ORDERDATE,STATUS,PRODUCTLINE,PRODUCTCODE,CUSTOMERNAME
0,10107,30,95.70,2,2871.00,2/24/2003 0:00,Shipped,Motorcycles,S10_1678,Land of Toys Inc.
1,10121,34,81.35,5,2765.90,5/7/2003 0:00,Shipped,Motorcycles,S10_1678,Reims Collectables
2,10134,41,94.74,2,3884.34,7/1/2003 0:00,Shipped,Motorcycles,S10_1678,Lyon Souveniers
3,10145,45,83.26,6,3746.70,8/25/2003 0:00,Shipped,Motorcycles,S10_1678,Toys4GrownUps.com
4,10159,49,100.00,14,5205.27,10/10/2003 0:00,Shipped,Motorcycles,S10_1678,Corporate Gift Ideas Co.
...,...,...,...,...,...,...,...,...,...,...
2818,10350,20,100.00,15,2244.40,12/2/2004 0:00,Shipped,Ships,S72_3212,Euro Shopping Channel
2819,10373,29,100.00,1,3978.51,1/31/2005 0:00,Shipped,Ships,S72_3212,"Oulu Toy Supplies, Inc."
2820,10386,43,100.00,4,5417.57,3/1/2005 0:00,Resolved,Ships,S72_3212,Euro Shopping Channel
2821,10397,34,62.24,1,2116.16,3/28/2005 0:00,Shipped,Ships,S72_3212,Alpha Cognac
2822,10414,47,65.52,9,3079.44,5/6/2005 0:00,On Hold,Ships,S72_3212,Gifts4AllAges.com

2. Inpeksi Awal Data:

a. Tampilkan 5 baris pertama dari dataset.

b. Gunakan .info() untuk melihat informasi dasar dataset.

In [ ]:
print(df.head())

   ORDERNUMBER  QUANTITYORDERED  PRICEEACH  ORDERLINENUMBER    SALES  \
0        10107               30      95.70                2  2871.00
1        10121               34      81.35                5  2765.90
2        10134               41      94.74                2  3884.34
3        10145               45      83.26                6  3746.70
4        10159               49     100.00               14  5205.27

         ORDERDATE   STATUS  PRODUCTLINE PRODUCTCODE              CUSTOMERNAME
0   2/24/2003 0:00  Shipped  Motorcycles    S10_1678         Land of Toys Inc.
1    5/7/2003 0:00  Shipped  Motorcycles    S10_1678        Reims Collectables
2    7/1/2003 0:00  Shipped  Motorcycles    S10_1678           Lyon Souveniers
3   8/25/2003 0:00  Shipped  Motorcycles    S10_1678         Toys4GrownUps.com
4  10/10/2003 0:00  Shipped  Motorcycles    S10_1678  Corporate Gift Ideas Co.

In [ ]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2823 entries, 0 to 2822
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   ORDERNUMBER      2823 non-null   int64
 1   QUANTITYORDERED  2823 non-null   int64
 2   PRICEEACH        2823 non-null   float64
 3   ORDERLINENUMBER  2823 non-null   int64
 4   SALES            2823 non-null   float64
 5   ORDERDATE        2823 non-null   object
 6   STATUS           2823 non-null   object
 7   PRODUCTLINE      2823 non-null   object
 8   PRODUCTCODE      2823 non-null   object
 9   CUSTOMERNAME     2823 non-null   object
dtypes: float64(2), int64(3), object(5)
memory usage: 220.7+ KB

3. Analisis Deskriptif:

a. Hitung total unit terjual menggunakan .sum() pada kolom Sales.

b. Temukan rata-rata unit terjual per transaksi.

In [ ]:
total_unit_terjual = df['SALES'].sum()
print("Total Unit Terjual:", total_unit_terjual)

Total Unit Terjual: 10032628.85

In [ ]:
avg = df['SALES'].mean()
print("Rata-rata Unit Terjual per Transaksi:", avg)

Rata-rata Unit Terjual per Transaksi: 3553.889071909316